spring : 
  application :
    name : ServerPrac
  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

